Initial commit of elasticsearch base image
caf-archive/opensuse-elasticsearch2-image pull request #1
Opened 2017-12-12 16:43 UTC by michael-bryson

2017-12-12 19:14 UTC, dermot-hardy requested changes

2017-12-12 19:14 UTC, dermot-hardy commented on src/main/docker/Dockerfile
> +COPY --from=builder /opt/elasticsearch-2.3.3/ /opt/elasticsearch/
Put the `COPY` command between the `CMD` command and the `ARG` commands.  This will make the build faster as it will make better use of the build cache.

2017-12-12 19:14 UTC, dermot-hardy commented on src/main/docker/Dockerfile
> +RUN zypper -n install unzip which hostname
Are `which` and `hostname` actually required in this image?

2017-12-12 19:14 UTC, dermot-hardy commented on src/main/docker/Dockerfile
> +CMD /opt/elasticsearch-2.3.3/bin/plugin install analysis-icu
This is just setting the default command.  I can't see when this would ever get run.  How do we test whether the `analysis-icu` plugin is getting correctly installed?

2017-12-13 08:41 UTC, michael-bryson commented on src/main/docker/Dockerfile
> +RUN zypper -n install unzip which hostname
Yes, the installation of the plugin required them

2017-12-13 08:42 UTC, michael-bryson commented on src/main/docker/Dockerfile
> +CMD /opt/elasticsearch-2.3.3/bin/plugin install analysis-icu
I have tried this with RUN but for some reason it does not work in the build, I can run it manually everytime. Could it be that it is trying to run it before the unzip is complete?

2017-12-13 08:43 UTC, michael-bryson commented on src/main/docker/Dockerfile
> +COPY --from=builder /opt/elasticsearch-2.3.3/ /opt/elasticsearch/
Moving the copy will not work as the elasticsearch folder will not exist on the image.

2017-12-13 13:08 UTC, dermot-hardy approved these changes

2017-12-13 13:08 UTC, dermot-hardy commented on src/main/docker/Dockerfile
> +CMD /opt/elasticsearch/bin/elasticsearch -Des.insecure.allow.root=true
If there is a way to set this `es.insecure.allow.root` property by default in one of the config files then we should probably do that, but we can leave it for now.

2017-12-13 13:08 UTC, merged